### PR TITLE
Modifications to storm module for BMI

### PR DESCRIPTION
**Pull request by anardek**
@mcflugen and @irbreeves, right now there are some issues with merging (I think I need to move some files around to different folders), but I finished cleaning up the MSSM model in Matlab and the storm time series generation codes in Python. Please see my notebook for an explanation of how to use.

@irbreeves, a couple Qs for you:
- where is Tp used in the model (i.e., why is it a part of StormSeries)? 
- why do we make TWL relative to MHW?  
- can you check the function shift_storm_intensity for correctness? this is just a rewrite of what was in `Barrier3D_MakeTimeSeries_TWL`; I removed all the hard-coded variables and pulled the information for a beta distribution directly from the distfit function. Should ` elif ST > simTWL[-1]:  # np.mean(simTWL):
                ST = simTWL[-1]  # np.mean(simTWL)` be replaced with the mean statements? is -1 indexing robust here?

### CODE REVIEW

**Comment by irbreeves** [comment]
Looks great.

- Tp was at one point used in overwash, but no longer. could be removed but I don’t see a problem leaving it either
- All other elevations are converted to the MHW datum in the parameter input file before they go into the main run file, so I had these water elevations converted here too
- It should be simTWL[-1]. The storm list should be sorted from lowest TWL to highest. So this line just says that the randomly-drawn TWL (ST) can’t be lower than the lowest observed TWL; otherwise, it would try to sample from a bin that doesn’t exist

**Comment by mcflugen** [comment]
@anardek It looks like the only files that have conflicts are those in the *V1_noBMI* folder. You've made changes to files in that folder on the *Barrier3d-v2.0* branch (you renamed *master*?) and on your *kanarde-storm-modifications* branch. I had a look but it wasn't clear to me exactly how the conflicts should be resolved so I didn't try. Maybe it's more clear to you? Let me know if you need any help.

**Comment by anardek** [comment]
@mcflugen So we had a meeting last week with the coauthors on Ian's MS and we decided for reproducibility of his GRL paper, he should upload the version of B3D that he used and all associated scripts as Version 1 and the BMI will be version 2. This is why we renamed the branches. I had started the kanarde-storm-modifications branch before we updated the V1_NoBMI folder (to match what is in the Barrier3D-v1.0 branch), and now I'm having a nightmare with black. As you can see from my commits above, I downloaded the new V1_NoBMI folder as is -- which is not formatted for black -- which I thought would fix the problem but it created more conflicts because my PyCharm reformatted every file for black. Is there any way to just accept my version (i.e., from kanarde-storm-modifications) of all theses files in V1_NoVMI so they are reformatted for black? I can't figure out how to do it in the web editor without manually deleting chunks for each file.

**Comment by anardek** [comment]
> * It should be simTWL[-1]. The storm list should be sorted from lowest TWL to highest. So this line just says that the randomly-drawn TWL (ST) can’t be lower than the lowest observed TWL; otherwise, it would try to sample from a bin that doesn’t exist

@irbreeves, ok -- that was the problem. The input storm series were not sorted (you must have done this manually in excel?). I added new code for this. Again, take a look at the notebook and let me know what you think.

**Comment by mcflugen** [comment]
@anardek See #17. I've reformatted the V1 files with *black*.

**Comment by anardek** [comment]
@mcflugen, one last thing: in the notebook, I can't access the "scripts" folder, and I'm not sure why. Any ideas?

**Comment by mcflugen** [comment]
@anardek What is the error you are getting? I suspect you may have started the notebook from the wrong folder.

**Comment by anardek** [comment]
Screen Shot 2021-05-07 at 2 47 03 PM

I've tried starting the notebook from the main folder and from within notebooks

**Comment by mcflugen** [comment]
@anardek I think we might want to do one of two things to help with this; both of which involve moving the python modules in the *Tools* and *scripts* folders. Either move them to:
1. the *notebooks* folder, or
2. the *barrier3d* package

If the functions in those modules are only for the notebooks, then number 1. If the functions are more broadly useful, then number 2.

What do you think?

**Comment by anardek** [comment]
I think #2: I'm just showing how to use the functions in the notebook. Can we create a `tools` folder in the *barrier3d* package? Then put the plotters, and MSSM module within that? Should we accept this pull request and then I can move things around on the master V2 branch?

**Comment by mcflugen** [comment]
Have you run `pip install -e .` from your *Barrier3D* folder while within your current *conda* environment? Something to check would be to run the following from your notebook,
```python
>>> import sys
>>> sys.path
```
and see if your *Barrier3D* folder is listed.

**Comment by anardek** [comment]
> Have you run `pip install -e .` from your _Barrier3D_ folder while within your current _conda_ environment? Something to check would be to run the following from your notebook,
> 
> ```python
> >>> import sys
> >>> sys.path
> ```
> 
> and see if your _Barrier3D_ folder is listed.

Yes, it is listed

**Comment by mcflugen** [comment]
> @mcflugen Lets go with #2: I'm just showing how to use the functions in the notebook. Can we create a `tools` folder in the _barrier3d_ package? Then put the plotters, and MSSM module within that? Should we accept this pull request and then I can move things around on the master V2 branch?

In that case, I think the best thing to do is to create a new folder under *barrier3d* (call it either *tools* or *utilities* or something like that) and move the two *.py* files into it. I would then move the data files your notebook uses into the *notebooks* folder—I don't think we want the data inside of the *barrier3d* package.

It's probably best to do all of this as a separate pull request.

**Comment by mcflugen** [comment]
> Yes, it is listed

I'm not sure what is going on, then. It seems like, somehow, your paths are getting mixed up. 🤔

**Pull request merged**
