### PR TITLE
Reorganize Barrier3D and compare BMI to Version 1

### PR DESCRIPTION
**Pull request by anardek**
@irbreeves 
- I tested the new Version 1 against the BMI ("see plot_BMI_vs_V1.py"); there is a very small mismatch in shoreline change. I'm not too worried about it. Take a look.
- do we still need tide_amp in the barrier3d_parameters file? 
- Once this pull request is accepted, we probably need to update the fancy Barrier3D readme with the new parameter file, and any other changes/additions (i.e., where the example scripts are located to run the different Versions, point to the notebook, do we specify that the elevation and dune input files need to be in units of dam?)
- 
@irbreeves and @mcflugen: 
- Ian and I go back and forth to change the directory paths in order to use the testing and example scripts, as well as in Version 1 of Barrier3D to specify where the input and parameter files are located on our personal machines. Is there a way around this? Something more sophisticated we can do?

### CODE REVIEW

**Comment by anardek** [comment]
@mcflugen ah yes, relative path names work. Think I changed most of them. Couldn't get relative path names to work in the notebook, but there is probably a way around that? maybe change directories at the beginning back to the main directory?

**Comment by mcflugen** [comment]
@anardek for the notebooks, I think I would create a data folder in the notebooks folder and then use relative pathnames.

I've added the relative pathnames to the notebook in the above commits but didn't create the data folder. I wasn't sure if all of the data files in the *tests/test_params* were necessary so I left that for you.

**Comment by anardek** [comment]
@mcflugen - the progress bar is AMAZING!  

Ok, all changes made that you suggested. Now to figure out why the checks aren't passing!

**Comment by mcflugen** [comment]
@anardek I can help out with the *flake8* tests. The main issue is that there are several functions in the *utilities* folder that aren't working. Is it ok if I move the unused and non-functional functions out of the *barrier3d* package? I can either move them back into the *Tools* (or *scripts*) folder or just remove them completely.

**Comment by anardek** [comment]
Ah, I see the plotters are screwing things up in Flake. Yes, I think it is fine to move them back to tools. I think it will screw with a bunch of directory pointers. Do you want to do it or me?

**Comment by mcflugen** [comment]
@anardek How about you give it a go? You probably have a better handle on the directory pointers. Let me know if you need help, though.

**Comment by anardek** [comment]
ok, @mcflugen - tried again. Looks like Flake is still failing.

**Comment by mcflugen** [comment]
@anardek no problem. I’ll fix it up.

**Comment by mcflugen** [comment]
@anardek I made a few small changes and now the *flake8* tests should pass.

I moved the utility functions you use in your notebook into *barrier3d/tools* and the rest into *old_tools* (which is ignored by *flake8* and *black*). I also updated the notebook to use the functions from the new location.

**Comment by anardek** [comment]
@mcflugen The 'Multivariate_Sea_Storm_Model' is not an old tool: it's actually the MSSM (I had to write it in Matlab for t_tide and some of the extreme stats functions). What is now in mssm.py is how we produce time series from the MSSM. I think its fine to just rename 'mssm.py' to 'create_input_files.py' or something similar, and put the last two functions from `Barrier3D_MakeTimeSeries` back in this file (I don't think these were what was causing Flake issues...plus, we use these functions often). I'm also fine breaking up Barrier3D_Plotting_Functions, many of which are not compatible yet with the BMI. The question then becomes, where do we put the `Multivariate_Sea_Storm_Model` folder?

**Comment by mcflugen** [comment]
@anardek To keep it as slim as possible, I only moved tools into the *barrier3d* package that I knew were being used. I figured you would move other functions you use into the *barrier3d/tools* folder.

I added the *old_tools* folder to indicate they are tools that may be broken but, in the future, could be fixed, moved into *barrier3d*, and used.

Some possibilities for the *Multivariate_Sea_Storm_Model* folder:
* a completely separate repository on GitHub
* a separate folder

If a separate folder in this repository, maybe: *mssm*, *matlab*, *multivariate_sea_storm_model*?

I renamed *mssm.py* to *input_file.py* but left off the *from_mssm* from the function names since they appear to be more general—they are (I think) reading generic data files that need not have been generated by the *mssm* script.

**Comment by anardek** [comment]
@mcflugen Gotcha! Yes, maybe the MSSM should be a separate repository (could be used by many programs, not just tailored to Barrier3D). I can work on that tomorrow.

**Comment by anardek** [comment]
@mcflugen, I made a separate repository for the MSSM and a couple other changes/additions that @irbreeves and I talked about on Friday. I think we are good to merge this pull request, but one last question: when I was updating load_inputs, I saw this huge block of code that is being ignored: I think it is old and can be deleted. Thoughts `    if params["InteriorDomain"].shape[1] > params["BarrierLength"]:
        params["InteriorDomain"] = params["InteriorDomain"][
            :, : params["BarrierLength"]
        ]
    else:
        params["BarrierLength"] = params["InteriorDomain"].shape[1]

    if False:
        z = params["InteriorDomain"] / 10.0 - params["MHW"]
        z[z <= 0.0] = -params["BayDepth"]
        # above_water = np.any(z > 0, axis=0)
        # z = z[:, above_water]
        # NOTE: if we haven't already flipped/rotated
        u = 1
        while u == 1:  # Remove all rows that have zero subaerial cells
            if all(z[:, -1] <= 0):
                z = z[:, :-1]
            else:
                u = 0
        # while np.all(z[:, -1] <= 0):
        #     z = z[:, :-1]
        # NOTE: if we have already flipped/rotated
        # u = 1
        # while u == 1:  # Remove all rows that have zero subaerial cells
        #     if all(z[0, :] <= 0):
        #         z = z[1:, :]
        #     else:
        #         u = 0

        # NOTE: We do this in the process step
        params["InteriorDomain"] = np.flipud(np.rot90(z))

        if len(params["InteriorDomain"][0]) > params["BarrierLength"]:
            # Reduce to specified max length
            params["InteriorDomain"] = params["InteriorDomain"][
                :, : params["BarrierLength"]
            ]
        else:
            params["BarrierLength"] = len(params["InteriorDomain"][0])
`

**Comment by mcflugen** [comment]
@anardek I suspect that can be removed. I don't recall why it was commented out but if things have been working fine with it as it is now, I don't see any harm in deleting it.

It looks like the *flake* tests are easy to fix but what about the other failing tests? Do you know what's going on there?

**Comment by anardek** [comment]
@irbreeves, see last comment; is this code from your old Barrier3d.py?

**Comment by mcflugen** [comment]
@anardek it looks like *barrier3d-parameters.yaml* was changed but *barrier3d-parameters.py* wasn't updated to match. I updated the latter to match to former. I hope I didn't get it backward.

**Pull request merged**
